<a href="https://colab.research.google.com/github/adedokun2016/IBM-Data-Science-Professional-Certificate/blob/main/Working_with_Data_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'5'+'6'

'56'

In [2]:
'hello'.upper()

'HELLO'

In [3]:
str(1+1)

'2'

In [4]:
"ABC".replace("AB", "ab")

'abC'

In [12]:
1+3*2

7

In [13]:
 A=((11,12),[21,22])
 A[1]

[21, 22]

In [14]:
A=((1),[2,3],[4])
A[2]

[4]

In [28]:
A=["hard rock",10,1.2]
del(A[1])
print(A)


['hard rock', 1.2]


In [23]:
 len(("disco",10))

2

In [27]:
V={'1','2'}
V.add('3')
print(V)

{'1', '2', '3'}


In [31]:
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt
import seaborn as sns
from contextlib import contextmanager
from time import time
from tqdm import tqdm
import lightgbm as lgbm
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import classification_report, log_loss, accuracy_score
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import KFold

In [34]:
a=np.array([-1,1])

b=np.array([1,1])

np.dot(a,b)

0

In [38]:
X=np.array([[1,0],[0,1]])

Y=np.array([[0,1],[1,0]])

Z=X+Y
print(Z)

[[1 1]
 [1 1]]


In [40]:
X=np.array([[1,0,1],[2,2,2]])

out=X[0:2,2]
print(out)

[1 2]


In [41]:
X=np.array([[1,0],[0,1]])

Y=np.array([[2,1],[1,2]])

Z=np.dot(X,Y)
print(Z)

[[2 1]
 [1 2]]


In [42]:
#Write to the file "Example.txt".

with open("Example.txt", "w") as writefile:
    writefile.write("This is line A\n")
    writefile.write("This is line B\n")


SyntaxError: invalid syntax (<ipython-input-42-ea908d63bdb0>, line 1)

In [ ]:
#Copy the contents of 'Example2.txt' to 'Example3.txt'.
with open('Example2.txt', 'r') as readfile:
    with open('Example3.txt', 'w') as writefile:
        for line in readfile:
            writefile.write(line)

In [44]:
1/2

0.5

In [45]:
'1,2,3,4'.split(',')

['1', '2', '3', '4']

In [49]:
if(x!=1):
    print('Hello')
else:
    print('Hi')
    print('Mike')


NameError: name 'x' is not defined

In [52]:
def add(x):
    return(x + x)

add(1)

2

In [53]:
for i in range(1, 5):
    if (i != 2):
        print(i)

1
3
4


In [61]:
class Rectangle(object):

  def __init__(self,width=2,height =3,color='r'):

    self.height=height

    self.width=width

    self.color=color

  def drawRectangle(self):

import matplotlib.pyplot as plt

plt.gca().add_patch(plt.Rectangle((0, 0),self.width, self.height ,fc=self.color))

plt.axis('scaled')
plt.show()

IndentationError: expected an indented block after function definition on line 11 (<ipython-input-61-61d7a0f13775>, line 13)

In [62]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a/b

<ipython-input-62-db39360a571b>:5: RuntimeWarning: divide by zero encountered in divide
  a/b


array([ 0., inf,  0., inf,  0.])

In [63]:
a = np.array([1, 1, 1, 1, 1])
a + 10

array([11, 11, 11, 11, 11])

In [64]:
#The line of code that opens a file in append mode is:
#In this mode, data is added to the end of the file without overwriting its existing contents.

with open("Example.txt", "a") as file1:

SyntaxError: invalid syntax (<ipython-input-64-df42ac989cda>, line 1)